const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const url = process.env.IOS_STUDY_URL || 'http://127.0.0.1:8877/system/examples/studies/ios-reading/';
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
    const checks = [], errors = [];
    const check = (condition, name) => { if (!condition) throw new Error(name); checks.push(name); };
    page.on('pageerror', error => errors.push(error.message));
    page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
    const click = id => page.locator(`#${id}`).click();
    const settle = () => page.waitForTimeout(350);
    await page.goto(url);
    check(await page.locator('#note-sheet').isHidden(), 'reading starts without an overlay');
    const original = await page.locator('#note-copy').innerText();
    await page.locator('#selection').focus(); await page.keyboard.press('Enter'); await settle();
    check(await page.locator('#note-sheet').isVisible() && await page.locator('#note-sheet').getAttribute('data-detent') === 'medium', 'keyboard selection opens medium sheet');
    check(await page.locator('#selection').evaluate(element => { const rect = element.getBoundingClientRect(); return rect.top >= document.querySelector('.app-nav').getBoundingClientRect().bottom && rect.bottom < document.querySelector('.sheet').getBoundingClientRect().top; }), 'selected sentence remains visible above medium sheet');
    check(await page.locator('#bottom-tools').isHidden(), 'sheet replaces bottom tool layer');
    const readingPosition = await page.locator('#reader').evaluate(element => element.scrollTop);
    await page.locator('#reader').evaluate(element => element.scrollTop = element.scrollHeight);
    check(await page.locator('[data-source="1"]').evaluate(element => element.getBoundingClientRect().bottom < document.querySelector('.sheet').getBoundingClientRect().top), 'underlying document can scroll its final source above nonmodal sheet');
    await page.locator('#reader').evaluate((element, value) => element.scrollTop = value, readingPosition);
    await click('text-size');
    check(await page.locator('#text-size').getAttribute('aria-pressed') === 'true', 'underlying navigation remains interactive in nonmodal sheet');
    await click('text-size');
    await page.locator('#grabber').focus(); await page.keyboard.press('Enter'); await settle();
    check(await page.locator('#note-sheet').getAttribute('data-detent') === 'large', 'keyboard grabber expands sheet');
    await click('grabber'); await settle();
    check(await page.locator('#note-sheet').getAttribute('data-detent') === 'medium', 'grabber returns to medium detent');
    await click('sheet-edit'); await settle();
    check(await page.locator('#note-form').isVisible() && await page.locator('#sheet-edit').isDisabled(), 'editing expands sheet and unchanged save is disabled');
    await page.locator('#note-input').fill('暂存的备注'); await page.keyboard.press('Escape');
    check(await page.locator('#note-sheet').isHidden(), 'Escape dismisses sheet');
    check(await page.locator('#selection').evaluate(element => element === document.activeElement), 'dismiss restores original trigger focus');
    await click('open-note'); await click('sheet-edit');
    check(await page.locator('#note-input').inputValue() === '暂存的备注', 'reopening edit restores unsaved draft');
    await click('close-sheet');
    check(await page.locator('#note-copy').innerText() === original && await page.locator('#note-form').isHidden(), 'cancel discards draft and returns to saved note');
    await click('sheet-edit'); await page.locator('#note-input').fill('   ');
    check(await page.locator('#sheet-edit').isDisabled(), 'blank note cannot save');
    const literal = '<img src=x onerror=alert(1)> 保留用户当前阅读位置';
    await page.locator('#note-input').fill(literal);
    await page.locator('#note-input').dispatchEvent('compositionstart');
    await page.locator('#note-input').dispatchEvent('keydown', { key: 'Enter', ctrlKey: true, isComposing: true });
    check(await page.locator('#note-form').isVisible() && await page.locator('#sheet-edit').isDisabled(), 'IME composition prevents saving');
    await page.locator('#note-input').dispatchEvent('compositionend');
    await page.locator('#note-input').press('Control+Enter');
    check(await page.locator('#note-copy').innerText() === literal && await page.locator('#note-copy img').count() === 0, 'keyboard save renders literal user text');
    await click('sheet-resolve');
    check(await page.locator('#sheet-state').innerText() === '已处理' && await page.locator('#note-status').innerText() === '1 条备注已处理', 'resolve updates note and document status');
    await click('sheet-resolve');
    check(await page.locator('#sheet-state').innerText() === '待处理', 'resolved note can reopen');
    await click('close-sheet'); await click('back-button');
    check(await page.locator('#library-view').isVisible() && await page.locator('#bottom-tools').isHidden(), 'back shows document list without stale tools');
    await click('open-document');
    check(await page.locator('#document-view').isVisible(), 'document list returns to reading');
    await page.locator('#reader').evaluate(element => element.scrollTop = element.scrollHeight);
    await page.locator('[data-source="1"]').click();
    check(await page.locator('#source-name').innerText() === 'MessageBubble.js' && await page.locator('#sheet-edit').isHidden(), 'source sheet shows correct read-only summary');
    await click('close-sheet'); await click('reduce-transparency');
    check(await page.locator('.glass').first().evaluate(element => getComputedStyle(element).backdropFilter === 'none'), 'reduced transparency uses opaque controls');
    await page.emulateMedia({ reducedMotion: 'reduce' }); await click('open-note');
    check(await page.locator('#note-sheet').evaluate(element => getComputedStyle(element).animationName === 'none' && getComputedStyle(element).transitionDuration === '0s'), 'reduced motion disables sheet animation');
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.locator('#grabber').evaluate(element => element.focus());
    const handle = await page.locator('#grabber').boundingBox();
    await page.mouse.move(handle.x + handle.width / 2, handle.y + 10); await page.mouse.down(); await page.mouse.move(handle.x + handle.width / 2, handle.y - 120, { steps: 10 }); await page.mouse.up(); await settle();
    check(await page.locator('#note-sheet').getAttribute('data-detent') === 'large', 'dragging handle upward expands sheet');
    await click('grabber'); await settle();
    const medium = await page.locator('#grabber').boundingBox();
    await page.mouse.move(medium.x + medium.width / 2, medium.y + 10); await page.mouse.down(); await page.mouse.move(medium.x + medium.width / 2, medium.y + 160, { steps: 10 }); await page.mouse.up();
    check(await page.locator('#note-sheet').isHidden(), 'dragging medium sheet down dismisses it');
    for (const width of [1440, 1024, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 844 }); await page.reload();
      await click('text-size'); await click('open-note'); await settle();
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.querySelector('.sheet-scroll').scrollWidth <= document.querySelector('.sheet-scroll').clientWidth), `${width}px enlarged-text sheet has no horizontal overflow`);
    }
    await page.setViewportSize({ width: 320, height: 568 }); await page.reload();
    await page.locator('#reader').evaluate(element => element.scrollTop = element.scrollHeight);
    check(await page.locator('[data-source="1"]').evaluate(element => element.getBoundingClientRect().bottom < document.querySelector('#bottom-tools').getBoundingClientRect().top), 'short mobile viewport can scroll last source above controls');
    await click('edit-note'); await settle();
    check(await page.locator('#sheet-edit').evaluate(element => { const rect = element.getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight; }), 'short mobile viewport keeps save action visible');
    await page.reload();
    check(await page.locator('#note-copy').innerText() === original, 'reload resets sample state');
    check(await page.locator('.study-guide img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)), 'all reference images load');
    await page.setViewportSize({ width: 1440, height: 1080 }); await page.reload();
    await page.screenshot({ path: path.join(__dirname, 'reading-desktop.png'), fullPage: true });
    await click('open-note'); await settle(); await page.locator('.device').screenshot({ path: path.join(__dirname, 'note-phone.png') });
    await click('sheet-edit'); await settle(); await page.locator('.device').screenshot({ path: path.join(__dirname, 'edit-phone.png') });
    await page.setViewportSize({ width: 390, height: 844 }); await page.reload(); await page.screenshot({ path: path.join(__dirname, 'reading-mobile.png') });
    await click('open-note'); await settle(); await page.screenshot({ path: path.join(__dirname, 'note-mobile.png') });
    check(errors.length === 0, 'no runtime or HTTP errors');
    fs.writeFileSync(path.join(__dirname, 'validation.json'), JSON.stringify({ date: new Date().toISOString(), checks, errors, scope: 'Chromium desktop and viewport emulation. Not native iOS, virtual keyboard, VoiceOver, backend persistence or visual acceptance.' }, null, 2) + '\n');
    console.log(JSON.stringify({ count: checks.length, checks, errors }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
